
project_id = "mxxtvtwcoplfajvazpav"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[functions.create-stripe-customer]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.get-customer-subscriptions]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

[functions.analyze-design]
verify_jwt = true

[functions.capture-screenshot]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = true

[functions.ingest-knowledge]
verify_jwt = true
