
project_id = "mxxtvtwcoplfajvazpav"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[functions.create-stripe-customer]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.get-customer-subscriptions]
verify_jwt = true

[functions.create-customer-portal]
verify_jwt = true

[functions.analyze-design]
verify_jwt = true

[functions.capture-screenshot]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = true

[functions.ingest-knowledge]
verify_jwt = true

[functions.problem-context-extractor]
verify_jwt = true

[functions.problem-semantic-matcher]
verify_jwt = true

[functions.test-claude-auth]
verify_jwt = true

[functions.goblin-analysis-orchestrator]
verify_jwt = true

[functions.goblin-model-claude-analyzer]
verify_jwt = true

[functions.goblin-model-synthesis]
verify_jwt = true

[functions.goblin-persona-prompt-builder]
verify_jwt = true

[functions.goblin-vision-screen-detector]
verify_jwt = true

[functions.get-images-by-session]
verify_jwt = true

[functions.goblin-model-gpt-analyzer]
verify_jwt = true

[functions.goblin-backfill-maturity-scores]
verify_jwt = true

[functions.goblin-maturity-monitor]
verify_jwt = false

[functions.figmant-analyze-design]
verify_jwt = false

[functions.analyze-figmant-design]
verify_jwt = false

[functions.figmant-check-subscription]
verify_jwt = true

[functions.figmant-create-session]
verify_jwt = true

[functions.figmant-upload-image]
verify_jwt = true

[functions.figmant-plugin-api]
verify_jwt = true

[functions.api-key-management]
verify_jwt = true

[functions.api-analysis-data]
verify_jwt = false
